CC=gcc
CFLAGS_COMMON=-Wall -g -I. -MMD -MF .$@.d
CFLAGS=$(CFLAGS_COMMON) -m32 -Os -ffreestanding -nostdinc -MMD -MF .$@.d
CFLAGS_HOST=$(CFLAGS_COMMON) -O2 -MMD -MF .$@.d
AS=as
ASFLAGS=-g --32
LD=ld
OBJCOPY=objcopy
DEPS=$(wildcard .*.d)

all: $(TARGET)

clean:
	rm -f $(CLEAN_FILES) $(DEPS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

%.o: %.s
	$(AS) $(ASFLAGS) -o $@ $<

%.bin: %
	$(OBJCOPY) -O binary $< $@

.PHONY: all clean

-include $(DEPS)
